name: Build

on:
  push:
    branches: [main]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: cd android && ./gradlew assembleRelease

  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: cd ios && pod install
      - run: xcodebuild -workspace AuthApp.xcworkspace -scheme AuthApp -sdk iphonesimulator
